# Generated by Django 6.0.2 on 2026-04-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Puesto')),
                ('responsabilidades', models.TextField(verbose_name='Responsabilidades (ISO 5.5.b)')),
                ('autoridades', models.TextField(verbose_name='Autoridades (ISO 5.5.c)')),
                ('competencias_requeridas', models.TextField(verbose_name='Competencias Requeridas (ISO 6.2.2)')),
                ('reporta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='a_m07_roles_permisos.perfilpuesto', verbose_name='Reporta a')),
                ('rol_sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Rol en Sistema (RBAC)')),
            ],
            options={
                'verbose_name': 'Perfil de Puesto',
                'verbose_name_plural': 'Perfiles de Puesto',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_digital', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma Digital')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('es_suplente_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suplentes', to=settings.AUTH_USER_MODEL, verbose_name='Suplente autorizado de')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empleado', to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='a_m07_roles_permisos.perfilpuesto', verbose_name='Perfil de Puesto')),
            ],
            options={
                'verbose_name': 'Perfil de Empleado',
                'verbose_name_plural': 'Perfiles de Empleados',
            },
        ),
    ]
