# Generated by Django 6.0.2 on 2026-04-29 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código del Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('PROCEDIMIENTO', 'Procedimiento'), ('INSTRUCTIVO', 'Instructivo de Trabajo'), ('FORMATO', 'Formato / Registro'), ('POLITICA', 'Política'), ('EXTERNO', 'Documento Externo / Norma')], default='PROCEDIMIENTO', max_length=30)),
                ('version', models.IntegerField(default=1, verbose_name='Versión Actual')),
                ('descripcion_cambios', models.TextField(blank=True, verbose_name='Descripción de Cambios (Justificación de la nueva versión)')),
                ('enlace_archivo', models.URLField(blank=True, max_length=500, verbose_name='Enlace al Archivo (Local o SharePoint)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador / En Desarrollo'), ('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado (Pendiente Publicación)'), ('VIGENTE', 'Vigente / Publicado'), ('OBSOLETO', 'Obsoleto / Retirado')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_proxima_revision', models.DateField(blank=True, null=True, verbose_name='Fecha de Próxima Revisión Programada')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_aprobados', to=settings.AUTH_USER_MODEL)),
                ('elaborado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_elaborados', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento del SGC',
                'verbose_name_plural': 'Control Documental del SGC',
                'unique_together': {('codigo', 'version')},
            },
        ),
    ]
