# Generated by Django 6.0.2 on 2026-05-06 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('descripcion', models.TextField(verbose_name='Descripción del Riesgo/Conflicto')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='BAJO', max_length=10, verbose_name='Nivel de Riesgo')),
                ('estatus', models.CharField(choices=[('ABIERTO', 'Abierto'), ('MITIGADO', 'Mitigado')], default='ABIERTO', max_length=15, verbose_name='Estatus')),
                ('usuario_reporta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracionImparcialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_declaracion', models.DateField(auto_now_add=True, verbose_name='Fecha de Declaración')),
                ('acepta_politicas', models.BooleanField(default=False, verbose_name='Acepto la Política de Imparcialidad')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones_m25', to=settings.AUTH_USER_MODEL, verbose_name='Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Mitigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_medida', models.TextField(verbose_name='Medida de Mitigación Aplicada')),
                ('fecha_implementacion', models.DateField(verbose_name='Fecha de Implementación')),
                ('conflicto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigaciones', to='h_m25_imparcialidad.conflictointeres', verbose_name='Conflicto Relacionado')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
        ),
    ]
