# Generated by Django 6.0.2 on 2026-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('fuente', models.CharField(choices=[('Interna', 'Interna'), ('Cliente', 'Cliente'), ('Auditoría', 'Auditoría'), ('Proveedor', 'Proveedor'), ('Ensayo', 'Ensayo'), ('Otro', 'Otro')], default='Interna', max_length=50)),
                ('tipo', models.CharField(choices=[('No Conformidad', 'No Conformidad'), ('Queja', 'Queja'), ('Hallazgo', 'Hallazgo'), ('Observación', 'Observación')], default='No Conformidad', max_length=50)),
                ('proceso', models.CharField(max_length=150)),
                ('severidad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Media', max_length=20)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En progreso', 'En progreso'), ('Verificación', 'Verificación'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('revisado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción (qué pasó)')),
                ('evidencia', models.TextField(blank=True, null=True, verbose_name='Evidencia / Referencia')),
                ('contencion', models.TextField(blank=True, null=True, verbose_name='Contención (acción inmediata)')),
                ('correccion', models.TextField(blank=True, null=True, verbose_name='Corrección')),
                ('why1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Why 1')),
                ('why2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Why 2')),
                ('why3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Why 3')),
                ('why4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Why 4')),
                ('why5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Why 5 (Causa raíz)')),
                ('causa_raiz', models.CharField(blank=True, max_length=255, null=True)),
                ('accion_correctiva', models.TextField(blank=True, null=True, verbose_name='Acción correctiva (plan)')),
                ('verificacion', models.TextField(blank=True, null=True, verbose_name='Verificación')),
                ('eficacia', models.TextField(blank=True, null=True, verbose_name='Eficacia')),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('firma', models.TextField(blank=True, null=True, verbose_name='Firma Base64')),
            ],
        ),
    ]
