# Generated by Django 6.0.2 on 2026-04-22 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoSOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Método / SOP')),
                ('tipo', models.CharField(choices=[('METODO', 'Método de Ensayo'), ('SOP', 'Procedimiento Operativo Estándar (SOP)'), ('INSTRUCTIVO', 'Instructivo de Trabajo')], default='METODO', max_length=20)),
                ('version', models.CharField(max_length=10, verbose_name='Versión Actual')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_proxima_revision', models.DateField(verbose_name='Próxima Revisión')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('EN_REVISION', 'En Revisión'), ('OBSOLETO', 'Obsoleto')], default='VIGENTE', max_length=20)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='metodos_sops/', verbose_name='Documento (PDF)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método o SOP',
                'verbose_name_plural': 'Métodos y SOPs',
                'ordering': ['-estado', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion', models.DateField(verbose_name='Fecha de Aprobación de la Validación/Verificación')),
                ('reporte_evidencia', models.FileField(blank=True, null=True, upload_to='validaciones_metodos/')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='e_m05_metodos_sops.metodosop')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validación/Verificación',
                'verbose_name_plural': 'Validaciones/Verificaciones',
            },
        ),
    ]
