# Generated by Django 6.0.2 on 2026-05-06 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del KPI')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Meta Esperada')),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Actual')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mr', models.CharField(max_length=50, unique=True, verbose_name='Código de Revisión')),
                ('fecha_revision', models.DateField(verbose_name='Fecha de Revisión')),
                ('resumen', models.TextField(verbose_name='Resumen Ejecutivo')),
                ('estatus', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=15, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='AcuerdoRMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(verbose_name='Acción / Recurso Asignado')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('estatus', models.CharField(choices=[('PENDING', 'Pendiente'), ('DONE', 'Realizado'), ('CLOSED', 'Cerrado')], default='PENDING', max_length=15, verbose_name='Estatus')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='h_m24_revision_direccion.revisiondireccion')),
            ],
        ),
    ]
