# Generated by Django 6.0.2 on 2026-04-28 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_informe', models.CharField(max_length=50, unique=True, verbose_name='Código del Informe')),
                ('tipo', models.CharField(choices=[('ENSAYO', 'Informe de Ensayo'), ('CALIBRACION', 'Certificado de Calibración')], max_length=20, verbose_name='Tipo de Documento')),
                ('fecha_emision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('EMITIDO', 'Emitido'), ('CANCELADO', 'Cancelado / Modificado')], default='BORRADOR', max_length=20)),
                ('declaracion_conformidad', models.TextField(blank=True, verbose_name='Declaración de Conformidad')),
                ('opiniones_interpretaciones', models.TextField(blank=True, verbose_name='Opiniones e Interpretaciones')),
                ('es_enmienda', models.BooleanField(default=False, verbose_name='Es una enmienda')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_creados', to=settings.AUTH_USER_MODEL)),
                ('informe_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enmiendas_generadas', to='f_m15_emision_informes.informecertificado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe / Certificado',
                'verbose_name_plural': 'Informes y Certificados',
            },
        ),
    ]
