# Generated by Django 6.0.2 on 2026-04-22 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_m05_metodos_sops', '0001_initial'),
        ('e_m12_ejecucion_registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoIncertidumbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='Versión del Presupuesto')),
                ('fecha_aprobacion', models.DateField(auto_now_add=True)),
                ('descripcion_modelo', models.TextField(verbose_name='Descripción de fuentes (Tipo A y B)')),
                ('factor_cobertura', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Factor k (95% confianza)')),
                ('formula_aplicada', models.TextField(blank=True, help_text='Fórmula para el cálculo combinado')),
                ('es_vigente', models.BooleanField(default=True)),
                ('aprobado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_incertidumbre', to='e_m05_metodos_sops.metodosop')),
            ],
            options={
                'verbose_name': 'Presupuesto de Incertidumbre',
                'verbose_name_plural': 'Presupuestos de Incertidumbre',
                'unique_together': {('metodo', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CalculoIncertidumbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_medicion', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Resultado de la Medición (y)')),
                ('incertidumbre_combinada', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Incertidumbre Combinada (uc)')),
                ('incertidumbre_expandida', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Incertidumbre Expandida (U)')),
                ('unidades', models.CharField(default='N/A', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('bloqueado', models.BooleanField(default=True, editable=False, help_text='Garantiza inmutabilidad ISO 17025')),
                ('calculado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculos_realizados', to=settings.AUTH_USER_MODEL)),
                ('registro_tecnico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo_incertidumbre', to='e_m12_ejecucion_registros.registrotecnico')),
                ('presupuesto_utilizado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_m13_calculos_incertidumbre.presupuestoincertidumbre')),
            ],
            options={
                'verbose_name': 'Cálculo de Incertidumbre',
                'verbose_name_plural': 'Cálculos de Incertidumbre',
            },
        ),
    ]
