# Generated by Django 6.0.2 on 2026-04-08 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Muestra')),
                ('descripcion', models.TextField(verbose_name='Descripción del ítem')),
                ('metodo_muestreo', models.CharField(max_length=200, verbose_name='Método de Muestreo (Ref. Documental)')),
                ('fecha_muestreo', models.DateTimeField(verbose_name='Fecha y Hora de Muestreo')),
                ('condiciones_ambientales', models.CharField(blank=True, help_text='Ej: 25°C, 45% HR', max_length=200, null=True)),
                ('responsable_muestreo', models.CharField(max_length=100, verbose_name='Realizado por')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CadenaCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('entregado_por', models.CharField(max_length=100)),
                ('recibido_por', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodias', to='c_m03_muestreo.muestra')),
            ],
        ),
    ]
