# Generated by Django 6.0.2 on 2026-02-24 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionImparcialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('acepta_imparcialidad', models.BooleanField(default=False)),
                ('acepta_confidentialidad', models.BooleanField(default=False)),
                ('acepta_privacidad', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('firma_imagen', models.ImageField(upload_to='firmas_m00/', verbose_name='Imagen de Firma')),
                ('prev_hash', models.CharField(max_length=64, verbose_name='Hash Anterior')),
                ('hash_registro', models.CharField(max_length=64, verbose_name='Hash Evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Declaración M00',
                'ordering': ['-created_at'],
            },
        ),
    ]
