# Generated by Django 6.0.2 on 2026-04-29 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ac', models.CharField(max_length=50, unique=True, verbose_name='Código (Ej. AC-001)')),
                ('origen', models.CharField(choices=[('AUDITORIA_INTERNA', 'Auditoría Interna'), ('AUDITORIA_EXTERNA', 'Auditoría Externa'), ('TNC', 'Trabajo No Conforme'), ('QUEJA', 'Queja de Cliente'), ('REVISION_DIRECCION', 'Revisión por la Dirección'), ('OTRO', 'Otro / Mejora Continua')], max_length=50, verbose_name='Origen de la No Conformidad')),
                ('referencia_origen', models.CharField(blank=True, max_length=100, verbose_name='Referencia (Ej. TNC-005, Informe Auditoría)')),
                ('fecha_apertura', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Apertura')),
                ('descripcion_no_conformidad', models.TextField(verbose_name='Descripción de la No Conformidad')),
                ('analisis_causa_raiz', models.TextField(blank=True, verbose_name='Análisis de Causa Raíz (Metodología usada ej. 5 Porqués)')),
                ('acciones_implementadas', models.TextField(blank=True, verbose_name='Acciones Correctivas Implementadas')),
                ('fecha_limite_implementacion', models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Implementación')),
                ('evaluacion_eficacia', models.TextField(blank=True, verbose_name='Evaluación de la Eficacia')),
                ('es_eficaz', models.BooleanField(default=False, verbose_name='¿La acción fue eficaz?')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('requiere_actualizar_riesgos', models.BooleanField(default=False, verbose_name='¿Requiere actualizar Riesgos/Oportunidades?')),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('ANALISIS_CAUSA', 'Análisis de Causa Raíz'), ('IMPLEMENTACION', 'En Implementación'), ('EVALUACION', 'Evaluando Eficacia'), ('CERRADA', 'Cerrada')], default='REGISTRADA', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_reportadas', to=settings.AUTH_USER_MODEL)),
                ('responsable_implementacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Implementación')),
            ],
            options={
                'verbose_name': 'Acción Correctiva y Mejora',
                'verbose_name_plural': 'Acciones Correctivas y Mejoras',
            },
        ),
    ]
