# Generated by Django 6.0.2 on 2026-04-22 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_m05_metodos_sops', '0001_initial'),
        ('e_m12_ejecucion_registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_qc', models.CharField(max_length=50, unique=True, verbose_name='Folio de Control (Ej. QC-2026-001)')),
                ('tipo_control', models.CharField(choices=[('BLANCO', 'Blanco de Reactivo / Muestra'), ('DUPLICADO', 'Duplicado de Ensayo'), ('MRC', 'Material de Referencia Certificado'), ('CIEGO', 'Muestra Ciega'), ('PT', 'Ensayo de Aptitud (Proficiency Testing)')], max_length=20)),
                ('fecha_ejecucion', models.DateField(verbose_name='Fecha de Ejecución del Control')),
                ('criterios_aceptacion', models.TextField(verbose_name='Criterios de Aceptación (Límites permitidos)')),
                ('resultados_obtenidos', models.TextField(verbose_name='Resultados Obtenidos (Datos crudos QC)')),
                ('es_conforme', models.BooleanField(default=True, verbose_name='¿El control es Conforme?')),
                ('evidencia_adjunta', models.FileField(blank=True, null=True, upload_to='qc_evidencias/', verbose_name='Evidencia Adjunta (Cartas de Control, Reportes PT)')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso (Editable)'), ('FINALIZADO', 'Finalizado (Bloqueado/Inmutable)')], default='EN_PROCESO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_realizados', to=settings.AUTH_USER_MODEL)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_m05_metodos_sops.metodosop', verbose_name='Método Evaluado')),
                ('registro_tecnico_asociado', models.ForeignKey(blank=True, help_text='Opcional: Lote de muestras asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_calidad', to='e_m12_ejecucion_registros.registrotecnico')),
            ],
            options={
                'verbose_name': 'Registro de Aseguramiento de Validez',
                'verbose_name_plural': 'Registros de Aseguramiento de Validez',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
