# Generated by Django 6.0.2 on 2026-03-24 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha / hora')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuario')),
                ('module', models.CharField(blank=True, max_length=100, null=True, verbose_name='Módulo')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acción')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('ok', models.BooleanField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
