# Generated by Django 6.0.2 on 2026-04-28 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoNoConforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tnc', models.CharField(max_length=50, unique=True, verbose_name='Código TNC (Ej. TNC-001)')),
                ('fecha_identificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Identificación')),
                ('descripcion_no_conformidad', models.TextField(verbose_name='Descripción del Trabajo No Conforme')),
                ('acciones_inmediatas', models.TextField(blank=True, verbose_name='Acciones Inmediatas Tomadas')),
                ('evaluacion_importancia', models.TextField(blank=True, verbose_name='Evaluación de la Importancia')),
                ('impacto', models.CharField(choices=[('BAJO', 'Bajo (Aceptable con desviación mínima)'), ('MEDIO', 'Medio (Requiere repetición o ajuste)'), ('ALTO', 'Alto (Afecta validez del resultado)')], default='BAJO', max_length=20)),
                ('decision_aceptabilidad', models.TextField(blank=True, verbose_name='Decisión sobre Aceptabilidad')),
                ('requiere_notificar_cliente', models.BooleanField(default=False, verbose_name='¿Requiere Notificar al Cliente?')),
                ('cliente_notificado', models.BooleanField(default=False, verbose_name='Cliente Notificado (Confirmación)')),
                ('fecha_reanudacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reanudación')),
                ('requiere_accion_correctiva', models.BooleanField(default=False, verbose_name='¿Genera Acción Correctiva?')),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado / Identificado'), ('EVALUACION', 'En Evaluación'), ('ACCION_TOMADA', 'Acciones Tomadas'), ('CERRADO', 'Cerrado')], default='REPORTADO', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autoriza_reanudar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tnc_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autoriza Reanudación del Trabajo')),
                ('identificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tnc_identificados', to=settings.AUTH_USER_MODEL)),
                ('responsable_evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tnc_evaluados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la Evaluación')),
            ],
            options={
                'verbose_name': 'Trabajo No Conforme',
                'verbose_name_plural': 'Trabajos No Conformes',
            },
        ),
    ]
