# Generated by Django 6.0.2 on 2026-04-01 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio de Solicitud')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('descripcion_solicitud', models.TextField(verbose_name='Descripción de la Solicitud')),
                ('metodo_ensayo', models.CharField(max_length=100, verbose_name='Método Solicitado')),
                ('capacidad_recursos', models.BooleanField(default=False, verbose_name='¿Tenemos capacidad y recursos?')),
                ('metodo_apropiado', models.BooleanField(default=False, verbose_name='¿El método es apropiado y vigente?')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios / Desviaciones')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Revisión de Contrato',
                'verbose_name_plural': 'Revisiones de Contratos',
            },
        ),
    ]
