# Generated by Django 6.0.2 on 2026-03-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoControlado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('tipo', models.CharField(default='Documento', max_length=50)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='Borrador', max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('cambios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrada_vigor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_revision', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta_vigente', models.CharField(blank=True, max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('elaborado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('revisado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_aprobacion', models.CharField(blank=True, max_length=50, null=True)),
                ('confidencialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobacion_estado', models.CharField(default='No enviado', max_length=50)),
            ],
        ),
    ]
