# Generated by Django 6.0.2 on 2026-03-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m05_control_documental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentocontrolado',
            old_name='observaciones',
            new_name='aprobacion_comentarios',
        ),
        migrations.RenameField(
            model_name='documentocontrolado',
            old_name='aprobado_por',
            new_name='aprobacion_resuelto_por',
        ),
        migrations.RenameField(
            model_name='documentocontrolado',
            old_name='confidencialidad',
            new_name='aprobacion_solicitado_por',
        ),
        migrations.RenameField(
            model_name='documentocontrolado',
            old_name='elaborado_por',
            new_name='confidencialidad_2',
        ),
        migrations.RemoveField(
            model_name='documentocontrolado',
            name='aprobacion_estado',
        ),
        migrations.RemoveField(
            model_name='documentocontrolado',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='documentocontrolado',
            name='fecha_entrada_vigor',
        ),
        migrations.RemoveField(
            model_name='documentocontrolado',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='documentocontrolado',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='documentocontrolado',
            name='revisado_por',
        ),
        migrations.RemoveField(
            model_name='documentocontrolado',
            name='ruta_vigente',
        ),
        migrations.AlterField(
            model_name='documentocontrolado',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentocontrolado',
            name='cambios',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentocontrolado',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='documentocontrolado',
            name='contenido',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentocontrolado',
            name='tipo',
            field=models.CharField(default='Documento', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentocontrolado',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
