# Generated by Django 6.0.2 on 2026-03-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoOportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=200, verbose_name='Proceso')),
                ('tipo', models.CharField(choices=[('Riesgo', 'Riesgo'), ('Oportunidad', 'Oportunidad')], default='Riesgo', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('causa', models.TextField(blank=True, null=True)),
                ('consecuencia', models.TextField(blank=True, null=True)),
                ('control_actual', models.TextField(blank=True, null=True, verbose_name='Control Actual')),
                ('accion_plan', models.TextField(blank=True, null=True, verbose_name='Acción Planificada')),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En progreso', 'En progreso'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('probabilidad', models.IntegerField(default=1, verbose_name='Probabilidad (1-5)')),
                ('impacto', models.IntegerField(default=1, verbose_name='Impacto (1-5)')),
                ('evidencia', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('revisado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('rol', models.CharField(default='Revisión/Aprobación', max_length=100)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='firmas_m06/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='m06_riesgos_oportunidades.riesgooportunidad')),
            ],
        ),
    ]
