# Generated by Django 6.0.2 on 2026-04-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_m05_metodos_sops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre del Curso/Capacitación')),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('INDUCCION', 'Inducción al SGC')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('instructor', models.CharField(max_length=100)),
                ('evidencia_pdf', models.FileField(blank=True, null=True, upload_to='capacitaciones/evidencias/')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('COMPLETADA', 'Completada'), ('VENCIDA', 'Vencida')], default='PROGRAMADA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacionMetodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_autorizacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Autorización Vigente')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmas_autorizacion', to=settings.AUTH_USER_MODEL)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_m05_metodos_sops.metodosop')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_metodos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorización de Método',
                'verbose_name_plural': 'Autorizaciones de Métodos',
                'unique_together': {('personal', 'metodo')},
            },
        ),
    ]
