# Generated by Django 6.0.2 on 2026-04-03 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio de la Queja (Ej. Q-2026-001)')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente o Empresa que reporta')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada de la queja')),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_INVESTIGACION', 'En Investigación'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada')], default='RECIBIDA', max_length=20)),
                ('acuse_recibo_enviado', models.BooleanField(default=False, verbose_name='¿Se envió acuse de recibo al cliente? (Cláusula 7.9.3)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recibida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibida por')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigacionQueja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis_causas', models.TextField(verbose_name='Análisis de Causas')),
                ('acciones_tomadas', models.TextField(verbose_name='Acciones Tomadas / Resolución')),
                ('fecha_resolucion', models.DateField(verbose_name='Fecha de Resolución')),
                ('notificacion_enviada', models.BooleanField(default=False, verbose_name='¿Se notificó formalmente el cierre al cliente? (Cláusula 7.9.6)')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la Investigación (Cláusula 7.9.5)')),
                ('queja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigacion', to='b_m17_gestion_quejas.queja')),
            ],
        ),
    ]
