# Generated by Django 6.0.2 on 2026-02-22 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('sistema', models.CharField(default='SGC ISO/IEC 17025', max_length=100)),
                ('tipo_documento', models.CharField(choices=[('Procedimiento', 'Procedimiento'), ('Instructivo', 'Instructivo'), ('Formato', 'Formato'), ('Manual', 'Manual'), ('Política', 'Política'), ('Plan', 'Plan')], max_length=50)),
                ('version', models.CharField(default='01', max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('vigencia_meses', models.IntegerField(default=24)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('OBSOLETO', 'Obsoleto')], default='BORRADOR', max_length=20)),
                ('fecha_firma_elaboro', models.DateField(blank=True, null=True)),
                ('fecha_firma_reviso', models.DateField(blank=True, null=True)),
                ('fecha_firma_aprobo', models.DateField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True)),
                ('alcance', models.TextField(blank=True)),
                ('responsabilidades', models.TextField(blank=True)),
                ('definiciones', models.TextField(blank=True)),
                ('procedimiento', models.TextField(blank=True)),
                ('registros', models.TextField(blank=True)),
                ('referencias', models.TextField(blank=True)),
                ('anexos', models.TextField(blank=True)),
                ('nota_control', models.TextField(default='Este documento es controlado. La versión vigente se encuentra disponible en el Sistema de Gestión del Laboratorio. Cualquier copia impresa se considera NO CONTROLADA.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_aprobo', to=settings.AUTH_USER_MODEL)),
                ('elaboro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_elaboro', to=settings.AUTH_USER_MODEL)),
                ('reviso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_reviso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Controlado',
                'verbose_name_plural': 'Documentos Controlados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistribucionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('copia_controlada', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion', to='m02_documentos.documento')),
            ],
            options={
                'verbose_name': 'Distribución',
            },
        ),
        migrations.CreateModel(
            name='CambioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('elaboro', models.CharField(max_length=100)),
                ('aprobo', models.CharField(max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='m02_documentos.documento')),
            ],
            options={
                'verbose_name': 'Control de Cambio',
            },
        ),
    ]
