# Generated by Django 6.0.2 on 2026-04-08 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True, verbose_name='ID Interno (Ej: MRC-001)')),
                ('nombre', models.CharField(max_length=150, verbose_name='Descripción del Material')),
                ('marca_fabricante', models.CharField(max_length=100, verbose_name='Fabricante / Instituto (Ej: NIST, CENAM)')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote No.')),
                ('certificado_numero', models.CharField(max_length=100, verbose_name='No. de Certificado')),
                ('incertidumbre', models.CharField(max_length=100, verbose_name='Valor de Incertidumbre y Cobertura (k=2)')),
                ('fecha_recepcion', models.DateField()),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField()),
                ('ubicacion', models.CharField(help_text='Ej: Refrigerador 2, Gaveta A', max_length=100)),
                ('condiciones_almacenamiento', models.CharField(help_text='Ej: 2 a 8 °C, Proteger de la luz', max_length=150)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente / Apto para uso'), ('CUARENTENA', 'En Cuarentena'), ('AGOTADO', 'Agotado / Consumido'), ('CADUCADO', 'Caducado / Fuera de uso')], default='VIGENTE', max_length=20)),
                ('archivo_certificado', models.FileField(blank=True, null=True, upload_to='certificados_mrc/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('motivo_uso', models.CharField(help_text='Ej: Verificación de balanza LABCOR-EQ-002, Ensayo X', max_length=200)),
                ('cantidad_utilizada', models.CharField(help_text='Ej: 5 ml, 1 ampolleta', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='d_m09_trazabilidad.materialreferencia')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
