# Generated by Django 6.0.2 on 2026-04-29 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_registro', models.CharField(max_length=50, unique=True, verbose_name='Código del Registro')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre o Título del Registro')),
                ('tipo', models.CharField(choices=[('TECNICO', 'Registro Técnico (Ensayos, Calibraciones)'), ('CALIDAD', 'Registro de Calidad (Auditorías, Revisiones)'), ('ADMINISTRATIVO', 'Registro Administrativo / Legal')], default='CALIDAD', max_length=30)),
                ('medio_almacenamiento', models.CharField(choices=[('FISICO', 'Físico (Papel / Carpeta)'), ('DIGITAL', 'Digital (Servidor / Nube)'), ('HIBRIDO', 'Híbrido (Ambos)')], default='DIGITAL', max_length=20)),
                ('ubicacion_almacenamiento', models.CharField(max_length=200, verbose_name='Ubicación Física o Ruta Lógica')),
                ('metodo_proteccion', models.CharField(default='Acceso restringido por rol y respaldos automatizados', max_length=200, verbose_name='Método de Protección')),
                ('tiempo_retencion_anios', models.PositiveIntegerField(default=5, verbose_name='Tiempo de Retención (Años)')),
                ('metodo_disposicion', models.CharField(choices=[('DESTRUCCION_FISICA', 'Destrucción Física (Triturado)'), ('BORRADO_SEGURO', 'Borrado Seguro de Datos'), ('ARCHIVO_PERMANENTE', 'Archivo Muerto Permanente')], default='BORRADO_SEGURO', max_length=30)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Vigente / Activo'), ('ARCHIVADO', 'Archivado (Retención en progreso)'), ('DESTRUIDO', 'Destruido / Eliminado Seguro')], default='ACTIVO', max_length=20)),
                ('fecha_creacion_registro', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Generación del Registro')),
                ('fecha_archivo', models.DateField(blank=True, null=True, verbose_name='Fecha en que se Archivó')),
                ('fecha_destruccion', models.DateField(blank=True, null=True, verbose_name='Fecha de Destrucción / Eliminación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Evidencia de Destrucción')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsable_custodia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_custodiados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de Registro',
                'verbose_name_plural': 'Control de Registros',
            },
        ),
    ]
