# Generated by Django 6.0.2 on 2026-04-03 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la Empresa o Razón Social')),
                ('rfc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RFC')),
                ('contacto_principal', models.CharField(max_length=150, verbose_name='Nombre del Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Es un cliente activo?')),
            ],
        ),
        migrations.CreateModel(
            name='AcuerdoConfidencialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de Firma del Acuerdo')),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('archivo_acuerdo', models.FileField(upload_to='acuerdos_confidencialidad/', verbose_name='Archivo (PDF)')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='b_m02_clientes.cliente')),
            ],
        ),
    ]
