# Generated by Django 6.0.2 on 2026-04-29 00:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoOportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ro', models.CharField(max_length=50, unique=True, verbose_name='Código (Ej. RO-001)')),
                ('tipo', models.CharField(choices=[('RIESGO', 'Riesgo'), ('OPORTUNIDAD', 'Oportunidad')], default='RIESGO', max_length=20)),
                ('origen', models.CharField(choices=[('AUDITORIA', 'Auditoría Interna/Externa'), ('REVISION_DIRECCION', 'Revisión por la Dirección'), ('TNC', 'Trabajo No Conforme'), ('QUEJA', 'Queja de Cliente'), ('OPERACION', 'Operación Diaria / Proceso'), ('CONTEXTO', 'Análisis de Contexto')], max_length=50)),
                ('fecha_identificacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Identificación')),
                ('descripcion', models.TextField(verbose_name='Descripción del Riesgo/Oportunidad')),
                ('probabilidad', models.IntegerField(choices=[(1, 'Bajo (1)'), (2, 'Medio (2)'), (3, 'Alto (3)')], default=1, verbose_name='Probabilidad')),
                ('impacto', models.IntegerField(choices=[(1, 'Bajo (1)'), (2, 'Medio (2)'), (3, 'Alto (3)')], default=1, verbose_name='Impacto')),
                ('acciones_planificadas', models.TextField(blank=True, verbose_name='Acciones Planificadas')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Implementación')),
                ('evaluacion_eficacia', models.TextField(blank=True, verbose_name='Evaluación de la Eficacia de las Acciones')),
                ('eficaz', models.BooleanField(default=False, verbose_name='¿Fueron eficaces las acciones?')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('PLANIFICACION', 'Planificación de Acciones'), ('IMPLEMENTACION', 'En Implementación'), ('EVALUACION', 'Evaluando Eficacia'), ('CERRADO', 'Cerrado')], default='IDENTIFICADO', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('identificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ro_identificados', to=settings.AUTH_USER_MODEL)),
                ('responsable_accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ro_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Implementación')),
            ],
            options={
                'verbose_name': 'Riesgo u Oportunidad',
                'verbose_name_plural': 'Riesgos y Oportunidades',
            },
        ),
    ]
