# Generated by Django 6.0.2 on 2026-02-16 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(choices=[('RECEPCION', 'Recepción'), ('ENSAYOS', 'Área de Ensayos'), ('ALMACEN', 'Almacén de Muestras'), ('OFICINAS', 'Oficinas Administrativas'), ('BANOS', 'Sanitarios')], max_length=50)),
                ('actividad', models.CharField(help_text='Ej: Barrido, Trapeado, Desinfección de superficies', max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpiezas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpiezas_verificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Limpieza',
                'verbose_name_plural': 'Bitácora de Limpieza',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
