# Generated by Django 6.0.2 on 2026-02-17 22:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m01_limpieza', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del activo o área', max_length=200)),
                ('area', models.CharField(help_text='Zona física (ej. Laboratorio A)', max_length=100)),
                ('frecuencia_dias', models.IntegerField(default=7, help_text='Cada cuántos días se debe limpiar')),
                ('checklist_default', models.TextField(blank=True, default='', help_text='Escribe las tareas de limpieza (una por línea).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Activo de Limpieza',
                'verbose_name_plural': 'Catálogo de Activos',
            },
        ),
        migrations.CreateModel(
            name='RegistroLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre_activo_snapshot', models.CharField(max_length=200)),
                ('area_snapshot', models.CharField(max_length=100)),
                ('tipo_limpieza', models.CharField(choices=[('RUTINA', 'Rutina'), ('PROFUNDA', 'Profunda'), ('DESINFECCION', 'Desinfección')], default='RUTINA', max_length=50)),
                ('frecuencia_aplicada', models.IntegerField()),
                ('proximo_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A TIEMPO', 'A Tiempo'), ('POR VENCER', 'Por Vencer'), ('VENCIDO', 'Vencido')], default='A TIEMPO', max_length=20)),
                ('checklist_realizado', models.TextField(blank=True, default='')),
                ('quimicos_usados', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('evidencia_pdf', models.FileField(blank=True, null=True, upload_to='evidencias/limpieza/')),
                ('activo_relacionado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='m01_limpieza.activolimpieza')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_limpieza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ejecución',
                'verbose_name_plural': 'Bitácora de Ejecuciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.DeleteModel(
            name='BitacoraLimpieza',
        ),
    ]
