# Generated by Django 6.0.2 on 2026-02-23 23:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio Cotización')),
                ('cliente', models.CharField(max_length=200)),
                ('ensayo', models.CharField(max_length=200)),
                ('norma', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='RevisionContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('fecha_revision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=200)),
                ('ensayo', models.CharField(max_length=200)),
                ('norma', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('alcance_confirmado', models.BooleanField(default=False, verbose_name='Alcance definido')),
                ('capacidad_laboratorio', models.BooleanField(default=False, verbose_name='Capacidad técnica')),
                ('recursos_disponibles', models.BooleanField(default=False, verbose_name='Recursos disponibles')),
                ('metodo_validado', models.BooleanField(default=False, verbose_name='Método validado')),
                ('incertidumbre_conocida', models.BooleanField(default=False, verbose_name='Incertidumbre conocida')),
                ('plazo_aceptado', models.BooleanField(default=False, verbose_name='Plazo aceptado')),
                ('revision_previa_ok', models.BooleanField(default=False, verbose_name='Revisión previa')),
                ('cambios_detectados', models.BooleanField(default=False, verbose_name='¿Cambios al contrato?')),
                ('descripcion_cambios', models.TextField(blank=True, null=True, verbose_name='Descripción de cambios')),
                ('aprobado', models.BooleanField(default=False)),
                ('aprobado_por', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hash_registro', models.CharField(blank=True, max_length=64)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='m03_revision_contrato.cotizacion')),
            ],
            options={
                'ordering': ['-fecha_revision'],
            },
        ),
    ]
