# Generated by Django 6.0.2 on 2026-04-22 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Área del Laboratorio')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('temp_min_permitida', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temp. Mínima (°C)')),
                ('temp_max_permitida', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temp. Máxima (°C)')),
                ('humedad_min_permitida', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humedad Mínima (%)')),
                ('humedad_max_permitida', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humedad Máxima (%)')),
            ],
            options={
                'verbose_name': 'Área de Laboratorio',
                'verbose_name_plural': 'Áreas de Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='RegistroAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Registro')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura Registrada (°C)')),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humedad Registrada (%)')),
                ('observaciones', models.TextField(blank=True, help_text='Anotar si hubo alguna desviación o equipo usado.', null=True)),
                ('cumple_criterio', models.BooleanField(default=True, editable=False, verbose_name='¿Dentro de especificación?')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='e_m07_condiciones_ambientales.arealaboratorio')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_ambientales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Ambiental',
                'verbose_name_plural': 'Registros Ambientales',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
