# Generated by Django 6.0.2 on 2026-05-05 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Auditoría')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Fecha Planeada')),
                ('performed_date', models.DateField(blank=True, null=True, verbose_name='Fecha Realizada')),
                ('scope', models.TextField(blank=True, verbose_name='Alcance')),
                ('status', models.CharField(choices=[('PLANNED', 'Planeada'), ('DONE', 'Realizada'), ('CLOSED', 'Cerrada')], default='PLANNED', max_length=20, verbose_name='Estatus')),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auditor Líder')),
            ],
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('NC', 'No Conformidad'), ('OBS', 'Observación'), ('OPPORTUNITY', 'Oportunidad de Mejora')], max_length=20, verbose_name='Tipo de Hallazgo')),
                ('description', models.TextField(verbose_name='Descripción del Hallazgo')),
                ('severity', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=20, null=True, verbose_name='Severidad')),
                ('related_process', models.CharField(blank=True, max_length=100, verbose_name='Proceso Relacionado')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='h_m23_auditorias_internas.internalaudit', verbose_name='Auditoría')),
            ],
        ),
    ]
