# Generated by Django 6.0.2 on 2026-03-03 22:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(default='SGC-DO-01', max_length=50, verbose_name='Código')),
                ('doc_title', models.CharField(default='Manual de Calidad y Procesos', max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido del Manual')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('OBSOLETO', 'Obsoleto')], default='BORRADOR', max_length=20, verbose_name='Estatus')),
                ('cambio_resumen', models.TextField(default='Creación inicial', verbose_name='Resumen de Cambios')),
                ('elaborado_por', models.CharField(max_length=150, verbose_name='Elaborado por')),
                ('aprobado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Aprobado por')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación')),
                ('fecha_vigencia', models.DateField(default=datetime.date.today, verbose_name='Fecha de Vigencia')),
                ('proxima_revision', models.DateField(blank=True, null=True, verbose_name='Próxima Revisión')),
            ],
        ),
        migrations.CreateModel(
            name='ManualDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Destinatario')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('copy_type', models.CharField(choices=[('CONTROLADA', 'Controlada'), ('NO CONTROLADA', 'No Controlada')], default='CONTROLADA', max_length=50, verbose_name='Tipo de Copia')),
                ('delivery_method', models.CharField(blank=True, max_length=100, verbose_name='Método de Entrega')),
                ('delivered_on', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('ack_received', models.BooleanField(default=False, verbose_name='Acuse Recibido')),
                ('ack_on', models.DateField(blank=True, null=True, verbose_name='Fecha de Acuse')),
                ('created_by', models.CharField(max_length=150, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='m04_manual.manualsgc')),
            ],
        ),
    ]
