# Generated by Django 6.0.2 on 2026-04-08 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('c_m03_muestreo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('conforme', models.BooleanField(default=True, verbose_name='¿Muestra cumple requisitos de ingreso?')),
                ('observaciones_integridad', models.TextField(blank=True, help_text='Describa anomalías o desviaciones (ISO 17025: 7.4.2)')),
                ('ubicacion_fisica', models.CharField(help_text='Ej: Refri 01, Estante B4', max_length=100)),
                ('condiciones_almacenamiento', models.CharField(help_text='Ej: Mantener a 4°C, Proteger de la luz', max_length=200)),
                ('estado_actual', models.CharField(choices=[('RECIBIDA', 'Recibida en Laboratorio'), ('PROCESO', 'En Análisis / Ensayo'), ('RETORNADA', 'Retornada al Cliente'), ('DESECHADA', 'Desechada / Eliminada')], default='RECIBIDA', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('muestra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion', to='c_m03_muestreo.muestra')),
                ('usuario_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(help_text='Ej: Movida a zona de desecho, Iniciado análisis', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='c_m04_recepcion.recepcionmuestra')),
            ],
            options={
                'verbose_name_plural': 'Historial de Manejo de Muestras',
            },
        ),
    ]
