# Generated by Django 6.0.2 on 2026-04-08 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True, verbose_name='ID Interno (Ej: LABCOR-EQ-001)')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(help_text='Ej: Área de Corrosión, Lab B', max_length=100)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Compra/Ingreso')),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo / Apto para uso'), ('CALIBRACION', 'En Proceso de Calibración'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio / No Conforme'), ('BAJA', 'Baja Definitiva')], default='OPERATIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calibracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calibracion', models.DateField()),
                ('proxima_calibracion', models.DateField()),
                ('certificado_numero', models.CharField(max_length=50, verbose_name='Número de Certificado')),
                ('resultado', models.CharField(help_text='Ej: Dentro de tolerancia / Incertidumbre +/- 0.1', max_length=100)),
                ('conforme', models.BooleanField(default=True)),
                ('archivo_certificado', models.FileField(blank=True, null=True, upload_to='certificados_calibracion/')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibraciones', to='d_m08_equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('tipo', models.CharField(choices=[('PREV', 'Preventivo'), ('CORR', 'Correctivo')], max_length=4)),
                ('descripcion', models.TextField(verbose_name='Detalles de la intervención')),
                ('proximo_mantenimiento', models.DateField()),
                ('realizado_por', models.CharField(help_text='Empresa externa o técnico interno', max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='d_m08_equipos.equipo')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
