# Generated by Django 6.0.2 on 2026-04-22 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_m05_metodos_sops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_registro', models.CharField(max_length=50, unique=True, verbose_name='Folio del Registro (Ej. RT-26-001)')),
                ('identificador_muestra', models.CharField(max_length=100, verbose_name='Identificación de la Muestra / Ítem')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio del Ensayo')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Finalización')),
                ('datos_crudos', models.TextField(help_text='Capture las lecturas directas del equipo. No modifique los datos posteriormente.', verbose_name='Observaciones Originales / Datos Crudos')),
                ('calculos_resultados', models.TextField(blank=True, null=True, verbose_name='Cálculos y Resultados Derivados')),
                ('evidencia_adjunta', models.FileField(blank=True, null=True, upload_to='registros_tecnicos/evidencias/', verbose_name='Evidencia Adjunta (Imágenes, XLSX)')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso (Borrador Editable)'), ('FINALIZADO', 'Finalizado (Bloqueado/Solo Lectura)'), ('REVISADO', 'Revisado por Calidad')], default='EN_PROCESO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ensayos_m12_ejecutados', to=settings.AUTH_USER_MODEL, verbose_name='Analista Responsable')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_m05_metodos_sops.metodosop', verbose_name='Método de Ensayo o SOP')),
            ],
            options={
                'verbose_name': 'Registro Técnico (E_m12)',
                'verbose_name_plural': 'Registros Técnicos (E_m12)',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
